FROM microsoft/aspnetcore-build AS build
WORKDIR /src
COPY *.csproj ./

RUN dotnet restore

COPY . ./
RUN dotnet build -c Release
#RUN dotnet test -c Release

FROM build AS publish
RUN dotnet publish -c Release
ENTRYPOINT ["dotnet", "test"]